-- Auto-generated from flags_resumen_total_con_pagos_galicia.csv
-- Inferred from first 2000 rows

CREATE TABLE IF NOT EXISTS `flags_resumen_total_con_pagos_galicia` (
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `motivos_no_pago` VARCHAR(255) NOT NULL,
  `tamano_archivo_kb` TINYINT NOT NULL,
  `CONTACTO_INDIRECTO_es_un_familiar_flg` TINYINT(1) NOT NULL,
  `CONTACTO_INDIRECTO_es_un_tercero_flg` TINYINT(1) NOT NULL,
  `CONTACTO_INDIRECTO_no_es_el_numero_flg` TINYINT(1) NOT NULL,
  `CONTACTO_INDIRECTO_no_se_encuentra_flg` TINYINT(1) NOT NULL,
  `Disposicion_desea_alguna_facilidad_flg` TINYINT(1) NOT NULL,
  `Disposicion_desea_en_cuotas_flg` TINYINT(1) NOT NULL,
  `Disposicion_desea_envio_de_informacion_flg` TINYINT(1) NOT NULL,
  `Disposicion_disposicion_a_pagar_flg` TINYINT(1) NOT NULL,
  `Disposicion_le_aprobaron_por_excepcion_flg` TINYINT(1) NOT NULL,
  `Disposicion_menciona_plazo_muy_corto_flg` TINYINT(1) NOT NULL,
  `Disposicion_monto_campana_alto_flg` TINYINT(1) NOT NULL,
  `Disposicion_no_es_flexible_esas_son_las_cuotas_minimas_flg` TINYINT(1) NOT NULL,
  `Disposicion_no_es_flexible_ese_monto_ofrecido_no_procede_flg` TINYINT(1) NOT NULL,
  `Disposicion_no_es_flexible_las_cuotas_aplican_sobre_el__6e182378` TINYINT(1) NOT NULL,
  `Disposicion_no_es_flexible_no_permite_mas_de_500_flg` TINYINT(1) NOT NULL,
  `Disposicion_no_es_flexible_no_se_puede_financiar_monto__97bf1111` TINYINT(1) NOT NULL,
  `Disposicion_pago_el_otro_ano_flg` TINYINT(1) NOT NULL,
  `Disposicion_propone_otra_fecha_de_pago_sin_seguridad_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_CAMPANA_ACTIVA_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_CAMPANA_EN_CUOTAS_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_OFRECER_CAMPANA_DE_CANCELACION_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_OFRECER_CAMPANA_DE_DESCUENTO_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_WHATSAPP_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_carta_de_cancelacion_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_carta_de_no_adeudo_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_comunicacion_cuenta_pendiente_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_exonerar_intereses_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_infocorp_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_plazo_de_campana_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_pregunta_inconvenientes_de_pago_flg` TINYINT(1) NOT NULL,
  `Informacion_campana_trate_de_reuinir_algun_importe_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_CANAL_DE_PAGO_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_DISMINUCION_DE_INGRESOS_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_Fallecimiento_de_familiar_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_Gastos_imprevistos_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_PRIORIZACION_OTRAS_DEUDAS_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_Robo_o_extorsion_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_TRABAJO_EVENTUAL_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_critico_DESEMPLEO_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_critico_PROBLEMA_DE_SALUD_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_critico_Problemas_economicos_no_especifica_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_critico_QUIEBRA_DE_NEGOCIO_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_embarazo_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_no_escucha_la_llamada_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_problemas_internos_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_telefono_malogrado_flg` TINYINT(1) NOT NULL,
  `Motivo_no_pago_viaje_flg` TINYINT(1) NOT NULL,
  `RECLAMO_desconfianza_en_informacion_flg` TINYINT(1) NOT NULL,
  `RECLAMO_estuvo_interesada_en_pagar_flg` TINYINT(1) NOT NULL,
  `RECLAMO_ninguna_ayuda_ni_soporte_flg` TINYINT(1) NOT NULL,
  `RECLAMO_reclamo_flg` TINYINT(1) NOT NULL,
  `RECLAMO_trato_prepotente_flg` TINYINT(1) NOT NULL,
  `RENUENTE_NO_QUIERE_PAGAR_flg` TINYINT(1) NOT NULL,
  `RENUENTE_enviara_notificaciones_legales_flg` TINYINT(1) NOT NULL,
  `RENUENTE_indica_llamar_despues_flg` TINYINT(1) NOT NULL,
  `RENUENTE_indica_lo_mismo_varios_meses_flg` TINYINT(1) NOT NULL,
  `RENUENTE_la_cobranza_va_a_continuar_flg` TINYINT(1) NOT NULL,
  `RENUENTE_no_escucha_o_se_hace_el_sordo_flg` TINYINT(1) NOT NULL,
  `RENUENTE_se_hace_pasar_por_un_tercero_o_es_el_titular_flg` TINYINT(1) NOT NULL,
  `RENUENTE_se_queda_sin_hablar_flg` TINYINT(1) NOT NULL,
  `RENUENTE_se_valida_que_si_esta_laborando_flg` TINYINT(1) NOT NULL,
  `SALUDO_saludo_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_acuerdo_de_devolucion_de_llamada_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_acuerdo_de_pago_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_ayer_conversamos_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_cuota_no_pagada_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_mal_pagador_flg` TINYINT(1) NOT NULL,
  `SEGUIMIENTO_no_ha_generado_acuerdo_de_pago_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_ingreso_adicional_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_propone_para_fin_de_mes_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_propone_para_la_proxima_semana_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_propone_para_quincena_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_propone_un_monto_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_recibio_liquidacion_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_se_compromete_a_realizar_el_pago_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_tendra_efectivo_para_fin_de_mes_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_tiene_trabajo_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_va_a_recibir_un_prestamo_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_vendio_terreno_flg` TINYINT(1) NOT NULL,
  `capacidad_de_pago_ya_estoy_pagando_flg` TINYINT(1) NOT NULL,
  `flag_agrupacion_CONTACTO_INDIRECTO` TINYINT(1) NOT NULL,
  `flag_agrupacion_Disposicion` TINYINT(1) NOT NULL,
  `flag_agrupacion_Informacion_campana` TINYINT(1) NOT NULL,
  `flag_agrupacion_Motivo_no_pago` TINYINT(1) NOT NULL,
  `flag_agrupacion_Motivo_no_pago_critico` TINYINT(1) NOT NULL,
  `flag_agrupacion_RECLAMO` TINYINT(1) NOT NULL,
  `flag_agrupacion_RENUENTE` TINYINT(1) NOT NULL,
  `flag_agrupacion_SALUDO` TINYINT(1) NOT NULL,
  `flag_agrupacion_SEGUIMIENTO` TINYINT(1) NOT NULL,
  `flag_agrupacion_capacidad_de_pago` TINYINT(1) NOT NULL,
  `grupos_motivos_no_pago` VARCHAR(255) NOT NULL,
  `Segmentacion_gestion` VARCHAR(255) NOT NULL,
  `detalle_segmentacion_gestion` VARCHAR(255) NOT NULL,
  `es_motivo_no_pago` TINYINT(1) NOT NULL,
  `conversation_id` VARCHAR(255) NOT NULL,
  `NOMBRE_AUDIO` VARCHAR(255) NOT NULL,
  `DATE` DATETIME NOT NULL,
  `TELEFONO` INT NOT NULL,
  `DOCUMENTO` INT NOT NULL,
  `ANEXO` DECIMAL(15,2) NULL,
  `ASESOR` DECIMAL(15,2) NULL,
  `fecha_conversacion` DATETIME NOT NULL,
  `codmes` INT NOT NULL,
  `monto_mejor_oferta` DECIMAL(15,2) NOT NULL,
  `PERIODO` DECIMAL(15,2) NULL,
  `IDENTITY_CODE` VARCHAR(255) NULL,
  `NUM_DOCUM_IDE` DECIMAL(15,2) NULL,
  `NUM_CUENTA_PMCP` DECIMAL(15,2) NULL,
  `PAGO` DECIMAL(15,2) NULL,
  `TIPO_CARTERA` VARCHAR(255) NULL,
  `FECHA_CASTIGO` DATETIME NULL,
  `CAPITAL` DECIMAL(15,2) NOT NULL,
  `DEUDA_TOTAL` DECIMAL(15,2) NOT NULL,
  `PCT_DSCTO` DECIMAL(15,2) NOT NULL,
  `LTD` DECIMAL(15,2) NOT NULL,
  `LTD_MEJOR` DECIMAL(15,2) NOT NULL,
  `MONTO_PAGO_TOTAL` DECIMAL(15,2) NOT NULL,
  `flg_pago` TINYINT(1) NOT NULL,
  `ESTUDIO_EXTERNO` VARCHAR(255) NOT NULL,
  `CTD_TOT` TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;