-- Auto-generated from flags_resumen_total_con_morosidad.csv
-- Inferred from first 2000 rows

CREATE TABLE IF NOT EXISTS `flags_resumen_total_con_morosidad` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `atributo_principal` VARCHAR(255) NOT NULL,
  `tamano_archivo_kb` TINYINT NOT NULL,
  `FLG_NO_CONTACTO_DIRECTO` TINYINT(1) NOT NULL,
  `FLG_YA_PAGO` TINYINT(1) NOT NULL,
  `FLG_PROMESA_CERRADA` TINYINT(1) NOT NULL,
  `gestor_Empatia_y_sonrrisa_telefonica_flg` TINYINT(1) NOT NULL,
  `gestor_Monto_fecha_o_dias_de_mora_flg` TINYINT(1) NOT NULL,
  `gestor_No_contacto_directo_flg` TINYINT(1) NOT NULL,
  `gestor_Ofrece_alternativas_adicionales_al_monto_de_la_deuda_flg` TINYINT(1) NOT NULL,
  `gestor_Promesa_cerrada_flg` TINYINT(1) NOT NULL,
  `gestor_Reprogramacion_de_deuda_flg` TINYINT(1) NOT NULL,
  `gestor_Servicio_al_cliente_flg` TINYINT(1) NOT NULL,
  `gestor_Tarjeta_garantia_flg` TINYINT(1) NOT NULL,
  `gestor_Utiliza_motivadores_de_pago_flg` TINYINT(1) NOT NULL,
  `gestor_Ya_cancelo_flg` TINYINT(1) NOT NULL,
  `gestor_sondear_al_cliente_indagar_flg` TINYINT(1) NOT NULL,
  `motivo_Cesante_flg` TINYINT(1) NOT NULL,
  `motivo_Cobro_de_membresia_flg` TINYINT(1) NOT NULL,
  `motivo_De_viaje_flg` TINYINT(1) NOT NULL,
  `motivo_Denuncia_flg` TINYINT(1) NOT NULL,
  `motivo_Deuda_de_terceros_flg` TINYINT(1) NOT NULL,
  `motivo_Fallecimiento_de_familiar_flg` TINYINT(1) NOT NULL,
  `motivo_Fecha_de_cobro_distinta_al_pago_flg` TINYINT(1) NOT NULL,
  `motivo_Fraude_flg` TINYINT(1) NOT NULL,
  `motivo_Garantia_flg` TINYINT(1) NOT NULL,
  `motivo_Gastos_imprevistos_flg` TINYINT(1) NOT NULL,
  `motivo_Hostigamiento_flg` TINYINT(1) NOT NULL,
  `motivo_Inconveniente_flg` TINYINT(1) NOT NULL,
  `motivo_Llaman_muchas_veces_flg` TINYINT(1) NOT NULL,
  `motivo_No_me_pagan_flg` TINYINT(1) NOT NULL,
  `motivo_No_quiere_pagar_por_alto_cobro_de_intereses_flg` TINYINT(1) NOT NULL,
  `motivo_No_recibio_estado_de_cuenta_flg` TINYINT(1) NOT NULL,
  `motivo_No_reconoce_la_deuda_flg` TINYINT(1) NOT NULL,
  `motivo_Olvido_flg` TINYINT(1) NOT NULL,
  `motivo_Paga_el_minimo_flg` TINYINT(1) NOT NULL,
  `motivo_Presento_reclamo_flg` TINYINT(1) NOT NULL,
  `motivo_Problemas_con_medios_de_pago_flg` TINYINT(1) NOT NULL,
  `motivo_Problemas_de_salud_flg` TINYINT(1) NOT NULL,
  `motivo_Problemas_economcos_no_especifica_flg` TINYINT(1) NOT NULL,
  `motivo_Promesa_cerrada_flg` TINYINT(1) NOT NULL,
  `motivo_Quiero_refinanciar_mi_deuda_flg` TINYINT(1) NOT NULL,
  `motivo_Quiero_reprogramar_mi_deuda_flg` TINYINT(1) NOT NULL,
  `motivo_Robo_o_extorsion_flg` TINYINT(1) NOT NULL,
  `motivo_Robo_o_perdida_flg` TINYINT(1) NOT NULL,
  `motivo_Ya_pago_flg` TINYINT(1) NOT NULL,
  `motivo_lo_deje_encargado_flg` TINYINT(1) NOT NULL,
  `flag_competencia_Conocimiento_del_producto` TINYINT(1) NOT NULL,
  `flag_competencia_Cualidades_del_buen_cobrador` TINYINT(1) NOT NULL,
  `flag_competencia_Exclusiones` TINYINT(1) NOT NULL,
  `flag_agrupacion_Problemas_de_flujo_corto_plazo` TINYINT(1) NOT NULL,
  `flag_agrupacion_Problemas_de_flujo_largo_plazo` TINYINT(1) NOT NULL,
  `flag_agrupacion_Problemas_operativos_cliente` TINYINT(1) NOT NULL,
  `flag_agrupacion_Promesa_cerrada` TINYINT(1) NOT NULL,
  `flag_agrupacion_Reclamo_del_cliente` TINYINT(1) NOT NULL,
  `flag_agrupacion_Ya_pago_o_no_expresa` TINYINT(1) NOT NULL,
  `conversation_id` VARCHAR(255) NOT NULL,
  `Cola` VARCHAR(255) NOT NULL,
  `Conclusion` VARCHAR(255) NOT NULL,
  `id_agente` VARCHAR(255) NOT NULL,
  `fecha_conversacion` DATETIME NULL,
  `id_cliente` VARCHAR(255) NULL,
  `codmes` DECIMAL(15,2) NULL,
  `nombre_agente` VARCHAR(255) NOT NULL,
  `DIAS_MORA` DECIMAL(15,2) NULL,
  `TIPO_PRODUCTO` DECIMAL(15,2) NULL,
  `SLD_CAPITAL` DECIMAL(15,2) NULL,
  `flg_mora30` TINYINT(1) NOT NULL,
  `flg_mora60` TINYINT(1) NOT NULL,
  `flg_mora90` TINYINT(1) NOT NULL,
  `tot` TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;