-- Auto-generated from resultados_analisis_completo_metadata_final_nps.csv
-- Inferred from first 2000 rows

CREATE TABLE IF NOT EXISTS `resultados_analisis_completo_metadata_final_nps` (
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `fecha_procesamiento` DATETIME NOT NULL,
  `motivo_Anular_tarjeta_flg` TINYINT(1) NOT NULL,
  `motivo_Bloqueo_tarjeta_flg` TINYINT(1) NOT NULL,
  `motivo_Carta_de_no_deudo_flg` TINYINT(1) NOT NULL,
  `motivo_Cliente_sin_atencion_flg` TINYINT(1) NOT NULL,
  `motivo_Consulta_Deuda_flg` TINYINT(1) NOT NULL,
  `motivo_Consulta_sobre_intereses_flg` TINYINT(1) NOT NULL,
  `motivo_Denuncia_flg` TINYINT(1) NOT NULL,
  `motivo_Donde_y_como_puedo_pagar_flg` TINYINT(1) NOT NULL,
  `motivo_Estado_de_cuenta_flg` TINYINT(1) NOT NULL,
  `motivo_Facilidad_de_pago_flg` TINYINT(1) NOT NULL,
  `motivo_Fallecimiento_flg` TINYINT(1) NOT NULL,
  `motivo_Fraude_flg` TINYINT(1) NOT NULL,
  `motivo_Intereses_altos_flg` TINYINT(1) NOT NULL,
  `motivo_Membresia_flg` TINYINT(1) NOT NULL,
  `motivo_Monto_para_pagar_flg` TINYINT(1) NOT NULL,
  `motivo_No_la_puedo_usar_o_no_la_uso_flg` TINYINT(1) NOT NULL,
  `motivo_Pago_minimo_flg` TINYINT(1) NOT NULL,
  `motivo_Perdida_de_tarjeta_flg` TINYINT(1) NOT NULL,
  `motivo_Presento_reclamo_flg` TINYINT(1) NOT NULL,
  `motivo_Prestamo_aprobado_flg` TINYINT(1) NOT NULL,
  `motivo_Problemas_con_medios_de_pago_flg` TINYINT(1) NOT NULL,
  `motivo_Refinanciacion_flg` TINYINT(1) NOT NULL,
  `motivo_Reprogramacion_flg` TINYINT(1) NOT NULL,
  `motivo_Seguro_flg` TINYINT(1) NOT NULL,
  `motivo_Traslado_de_deuda_a_estudio_flg` TINYINT(1) NOT NULL,
  `motivo_fecha_de_pago_flg` TINYINT(1) NOT NULL,
  `motivo_no_debo_nada_flg` TINYINT(1) NOT NULL,
  `flag_agrupacion_Anular_tarjeta` TINYINT(1) NOT NULL,
  `flag_agrupacion_Bloqueo_Perdida_Robo_Fraude` TINYINT(1) NOT NULL,
  `flag_agrupacion_Carta_de_no_deudo` TINYINT(1) NOT NULL,
  `flag_agrupacion_Estado_de_cuenta` TINYINT(1) NOT NULL,
  `flag_agrupacion_Facilidad_de_pago` TINYINT(1) NOT NULL,
  `flag_agrupacion_Informacion_deuda_cuota_o_fecha` TINYINT(1) NOT NULL,
  `flag_agrupacion_Medios_de_Pago` TINYINT(1) NOT NULL,
  `flag_agrupacion_Prestamo_` TINYINT(1) NOT NULL,
  `flag_agrupacion_Problemas_de_salud_o_Fallecimiento` TINYINT(1) NOT NULL,
  `flag_agrupacion_Reclamo_del_cliente` TINYINT(1) NOT NULL,
  `flag_agrupacion_Reprogramar_o_Refinanciar` TINYINT(1) NOT NULL,
  `flag_agrupacion_Seguro_Membresia_e_intereses` TINYINT(1) NOT NULL,
  `flag_agrupacion_Traslado_de_deuda_a_estudio` TINYINT(1) NOT NULL,
  `flag_agrupacion_Uso_tarjeta` TINYINT(1) NOT NULL,
  `motivo_Cliente_molesto_flg` TINYINT(1) NULL,
  `motivo_Cliente_satisfecho_flg` TINYINT(1) NULL,
  `flag_agrupacion_Satisfaccion_al_cliente` TINYINT(1) NULL,
  `archivo_multimedia` VARCHAR(255) NOT NULL,
  `conversation_id` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `customer_min_total` DECIMAL(15,2) NOT NULL,
  `customer_sin_callback_min` DECIMAL(15,2) NOT NULL,
  `ivr_min_total` DECIMAL(15,2) NOT NULL,
  `acd_min` DECIMAL(15,2) NOT NULL,
  `acd_callback_min` DECIMAL(15,2) NOT NULL,
  `agent_min` DECIMAL(15,2) NOT NULL,
  `agent_callback_min` DECIMAL(15,2) NOT NULL,
  `agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_RETENCION_agent_interact_ord` TINYINT NOT NULL,
  `AG_COBRANZAS_INBOUND_agent_interact_ord` TINYINT NOT NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_agent_interact_ord` TINYINT NOT NULL,
  `AG_FOH_COBRANZAS_ATC_agent_interact_ord` TINYINT NOT NULL,
  `FOH_TOH_ATC_agent_interact_ord` TINYINT NOT NULL,
  `AG_FOH_ATC_ANEXOS_agent_interact_ord` TINYINT NOT NULL,
  `agent_colas_cobranzas_interact_ctd` TINYINT NOT NULL,
  `agent_colas_atc_interact_ctd` TINYINT NOT NULL,
  `EPA_ATC_min` DECIMAL(15,2) NOT NULL,
  `EPA_COBRANZA_PE_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_RETENCION_acd_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_RETENCION_agent_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_RETENCION_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_acd_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_agent_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_first_interact_sec` DECIMAL(15,2) NULL,
  `AG_COBRANZAS_INBOUND_last_wrapup_sec` DECIMAL(15,2) NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_acd_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_agent_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_first_interact_sec` DECIMAL(15,2) NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_last_wrapup_sec` DECIMAL(15,2) NULL,
  `AG_COBRANZAS_INBOUND_CALLBACK_agent_callback_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_COBRANZAS_ATC_acd_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_COBRANZAS_ATC_agent_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_COBRANZAS_ATC_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_COBRANZAS_ATC_first_interact_sec` DECIMAL(15,2) NULL,
  `AG_FOH_COBRANZAS_ATC_last_wrapup_sec` DECIMAL(15,2) NULL,
  `FOH_TOH_ATC_acd_min` DECIMAL(15,2) NOT NULL,
  `FOH_TOH_ATC_agent_min` DECIMAL(15,2) NOT NULL,
  `FOH_TOH_ATC_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `FOH_TOH_ATC_first_interact_sec` DECIMAL(15,2) NULL,
  `FOH_TOH_ATC_last_wrapup_sec` DECIMAL(15,2) NULL,
  `AG_FOH_ATC_ANEXOS_acd_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_ATC_ANEXOS_agent_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_ATC_ANEXOS_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `AG_FOH_ATC_ANEXOS_first_interact_sec` DECIMAL(15,2) NULL,
  `AG_FOH_ATC_ANEXOS_last_wrapup_sec` DECIMAL(15,2) NULL,
  `conclusion_AG_COBRANZAS_INBOUND` VARCHAR(255) NULL,
  `conclusion_AG_COBRANZAS_INBOUND_CALLBACK` VARCHAR(255) NULL,
  `conclusion_AG_FOH_COBRANZAS_ATC` VARCHAR(255) NULL,
  `conclusion_FOH_TOH_ATC` VARCHAR(255) NULL,
  `conclusion_AG_FOH_ATC_ANEXOS` VARCHAR(255) NULL,
  `otras_colas_acd_min` DECIMAL(15,2) NOT NULL,
  `otras_colas_agent_min` DECIMAL(15,2) NOT NULL,
  `otras_colas_agent_interact_min` DECIMAL(15,2) NOT NULL,
  `conclusion_consolidada` VARCHAR(255) NOT NULL,
  `Grupo_Conclusion` VARCHAR(255) NOT NULL,
  `codmes` INT NOT NULL,
  `PREGUNTA` VARCHAR(255) NULL,
  `RESPUESTA` DECIMAL(15,2) NOT NULL,
  `FLG_BUENO` TINYINT(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;